/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_flexwintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "floatpos.c"
#include "focusmaster.c"
#include "moveplace.c"
#include "pertag.c"
#include "reorganizetags.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "selfrestart.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swaptags.c"
#include "tagall.c"
#include "tagothermonitor.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_tile.c"
